name: Build C Library

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-20.04, ubuntu-latest]
        arch: [arm64, armhf, x86_64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU for ARM emulation
      if: matrix.arch != 'x86_64'
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Set up GCC
      run: sudo apt-get install -y gcc

    - name: Build C library
      run: gcc -o libnetat libnetat.c

    - name: Display architecture
      run: echo "Architecture: ${{ matrix.arch }}"
